/* eslint-disable react/no-unknown-property */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const AXE_ROTATION = [0, Math.PI / 1.8, -0.3] as const;
const AXE_SCALE = 0.5;

type AxeGLTF = {
  nodes: {
    Mesh_1001_1: THREE.Mesh<THREE.BufferGeometry, THREE.MeshStandardMaterial>;
    Mesh_1001_2: THREE.Mesh<THREE.BufferGeometry, THREE.MeshStandardMaterial>;
  };
  materials: {
    material_2: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/axe.glb") as unknown as AxeGLTF;
  return (
    <group dispose={null} {...props}>
      <group rotation={AXE_ROTATION} scale={AXE_SCALE}>
        <mesh
          geometry={nodes.Mesh_1001_1.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Mesh_1001_2.geometry}
          material={materials.material_3}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/axe.glb");
